# Generated by Django 2.2.7 on 2019-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_password',
            field=models.BooleanField(default=True),
        ),
    ]
