# Generated by Django 2.2.7 on 2020-01-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200103_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
