# Generated by Django 2.2.7 on 2021-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200106_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
