# Generated by Django 2.2.7 on 2019-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
