# Generated by Django 2.2.7 on 2019-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='INT', max_length=10),
        ),
    ]
