# Generated by Django 2.2.7 on 2019-12-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_district'),
        ('projects', '0002_project_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='municipal',
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.District'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INT', 'Initiated'), ('ONG', 'Ongoing'), ('CMP', 'Completed')], default='INT', max_length=10),
        ),
    ]
