# Generated by Django 2.2.7 on 2019-11-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191130_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='minicipal',
            new_name='municipal',
        ),
    ]
