# Generated by Django 2.2.7 on 2019-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quantity_demanded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Demanded(Tons)'),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity_supplied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Supplied(Tons)'),
        ),
    ]
