# Generated by Django 2.2.7 on 2019-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191130_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
