# Generated by Django 2.2.7 on 2019-12-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_authority_consultant_contractor_financer_supplier'),
        ('projects', '0005_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.Authority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Duration(Years)'),
        ),
        migrations.CreateModel(
            name='ProjectSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price(TZS)')),
                ('remarks', models.CharField(max_length=255, verbose_name='Specific Requirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_suppliers', to='projects.Project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_suppliers', to='setups.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_financers', to='setups.Financer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_financers', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_contractor', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contractors', to='setups.Contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contractors', to='projects.Project')),
            ],
        ),
    ]
