# Generated by Django 2.2.7 on 2019-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191205_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsupplier',
            name='remarks',
        ),
        migrations.AddField(
            model_name='projectsupplier',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity(Tons)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Duration (Years)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity_demanded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Demanded (Tons)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity_supplied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Supplied (Tons)'),
        ),
    ]
