# Generated by Django 2.2.7 on 2019-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191205_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
