# Generated by Django 2.2.7 on 2019-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20191206_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
