# Generated by Django 2.2.7 on 2019-12-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191207_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaudit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
