# Generated by Django 2.2.7 on 2019-12-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectaudit_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectaudit',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='projectcontractor',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.Contractor'),
        ),
        migrations.AlterField(
            model_name='projectcontractor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractors', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectfinancer',
            name='financer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.Financer'),
        ),
        migrations.AlterField(
            model_name='projectfinancer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.Supplier'),
        ),
    ]
