# Generated by Django 2.2.7 on 2019-12-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_district'),
        ('projects', '0013_auto_20191209_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectconsultant',
            unique_together={('project', 'consultant')},
        ),
        migrations.AlterUniqueTogether(
            name='projectcontractor',
            unique_together={('project', 'contractor')},
        ),
        migrations.AlterUniqueTogether(
            name='projectfinancer',
            unique_together={('project', 'financer')},
        ),
        migrations.AlterUniqueTogether(
            name='projectsupplier',
            unique_together={('project', 'supplier')},
        ),
    ]
