# Generated by Django 2.2.7 on 2019-12-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_district'),
        ('projects', '0014_auto_20191209_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsupplier',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='setups.Supplier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INT', 'Initiated'), ('ONG', 'Ongoing'), ('CMP', 'Completed'), ('STP', 'Stopped')], default='INT', max_length=10),
        ),
    ]
