# Generated by Django 2.2.7 on 2019-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaudit',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='demanded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='supplied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
