# Generated by Django 2.2.7 on 2019-12-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_pics'),
        ),
    ]
