# Generated by Django 2.2.7 on 2021-05-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price/t (TZS)'),
        ),
    ]
