# Generated by Django 2.2.7 on 2021-05-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20210527_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsupplier',
            name='brand',
        ),
    ]
