# Generated by Django 2.2.7 on 2021-05-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_brand'),
        ('projects', '0027_remove_projectsupplier_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsupplier',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='setups.Brand'),
        ),
    ]
