# Generated by Django 2.2.7 on 2021-06-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_brand'),
        ('projects', '0030_auto_20210604_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsupplier',
            unique_together={('project', 'brand')},
        ),
        migrations.RemoveField(
            model_name='projectsupplier',
            name='supplier',
        ),
    ]
