# Generated by Django 2.2.7 on 2021-06-04 05:22

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20210604_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsupplier',
            name='supplier',
            field=core.models.UpperCaseCharField(blank=True, max_length=255, null=True),
        ),
    ]
