# Generated by Django 2.2.7 on 2021-06-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20210604_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsupplier',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='setups.Brand'),
        ),
    ]
