# Generated by Django 2.2.7 on 2021-06-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210605_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setups.Supplier'),
        ),
    ]
