# Generated by Django 2.2.7 on 2019-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_authority_consultant_contractor_financer_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='financer',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
