# Generated by Django 2.2.7 on 2019-12-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name_plural': 'Authorities'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
