# Generated by Django 2.2.7 on 2021-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0008_auto_20191219_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='group',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
