# Generated by Django 2.2.7 on 2021-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0009_status_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=40, null=True)),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
