# Generated by Django 2.2.7 on 2021-06-04 05:34

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=core.models.UpperCaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='financer',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=core.models.UpperCaseCharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=core.models.UpperCaseCharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=core.models.UpperCaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=core.models.UpperCaseCharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='group',
            field=core.models.UpperCaseCharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=core.models.UpperCaseCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=core.models.UpperCaseCharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=core.models.UpperCaseCharField(max_length=40, unique=True),
        ),
    ]
