# Generated by Django 2.2.7 on 2021-06-05 06:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0011_auto_20210604_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.models.UpperCaseCharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=40, null=True)),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
