# Generated by Django 2.2.7 on 2020-01-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popinfo', '0002_auto_20200106_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='winner',
            new_name='win',
        ),
        migrations.RenameField(
            model_name='win',
            old_name='name',
            new_name='winner_name',
        ),
    ]
